from pathlib import Path

path = Path('.tmp/create-etf-100-youtube-phase1.mjs')
text = path.read_text(encoding='utf-8')
start = text.index('const motionCode =')
end = text.index('const promptFor =', start)

replacement = r'''const motionCode = (v, n) => {
  const m = v.motion;
  const exp = `YouTubeVisual${idx(n)}Animation`;
  const q = (s) => JSON.stringify(s);
  const header = `import React from 'react';\nimport {AbsoluteFill, interpolate, spring, useCurrentFrame, useVideoConfig} from 'remotion';\n\nexport const MECHANIC_ID = ${q(m.mechanic)};\nexport const VISUAL_TECHNIQUE_ID = ${q(m.tech)};\nexport const COMPOSITION_FAMILY_ID = ${q(m.family)};\nexport const ANIMATION_NARRATIVE = {START:${q(m.beats[0])}, MECHANISM:${q(m.beats.slice(1,-1).join(' → ') || m.beats[1])}, RESULT:${q(m.beats[m.beats.length-1])}};\nconst C={bg:'#000000',green:'#22E08A',mint:'#9AF5CB',gold:'#F2C66D',red:'#FF6B4A',white:'#F7F5EF',muted:'#A9B3AE'};\nconst clamp={extrapolateLeft:'clamp',extrapolateRight:'clamp'} as const;\n`;
  let body = '';
  if (m.family === 'spatial-3d') {
    body = `import {ThreeCanvas} from '@remotion/three';\n\nexport const ${exp}:React.FC=()=>{const f=useCurrentFrame();const {fps}=useVideoConfig();const p=interpolate(f,[0,90],[0,1],clamp);const s=spring({frame:f-8,fps,config:{damping:16}});return <AbsoluteFill style={{background:C.bg}}><ThreeCanvas width={1920} height={1080} camera={{position:[0,0,8],fov:42}}><ambientLight intensity={1.2}/><directionalLight position={[4,6,8]} intensity={2}/><group rotation={[0,p*0.45,0]} scale={0.85+0.15*s}><mesh position={[-2.4,0,0]}><boxGeometry args={[2.2,1.2,0.45]}/><meshStandardMaterial color={C.green}/></mesh><mesh position={[0,0,0.5]}><boxGeometry args={[2.5,1.45,0.5]}/><meshStandardMaterial color={C.gold}/></mesh><mesh position={[2.5,0,0]}><boxGeometry args={[2.2,1.2,0.45]}/><meshStandardMaterial color={C.mint}/></mesh></group></ThreeCanvas><div style={{position:'absolute',bottom:90,width:'100%',textAlign:'center',fontSize:48,fontWeight:800,color:C.white}}>${m.intent}</div></AbsoluteFill>};\n`;
  } else if (m.family === 'vector-motion') {
    body = `export const ${exp}:React.FC=()=>{const f=useCurrentFrame();const p=interpolate(f,[0,90],[0,1],clamp);const sel=interpolate(f,[18,65],[0,1],clamp);return <AbsoluteFill style={{background:C.bg,alignItems:'center',justifyContent:'center'}}><svg width="1500" height="650" viewBox="0 0 1500 650">{Array.from({length:18}).map((_,i)=>{const x=90+(i%9)*150;const y=120+Math.floor(i/9)*220;const chosen=i%3!==2;const tx=chosen?520+(i%6)*95:x;const ty=chosen?420+(i%2)*80:y;return <g key={i} transform={'translate('+(x+(tx-x)*sel)+' '+(y+(ty-y)*sel)+')'}><rect x={-42} y={-28} width={84} height={56} rx={14} fill={chosen?C.green:C.muted} opacity={chosen?0.9:1-sel*0.75}/></g>})}<path d="M180 320 C520 140 980 140 1320 320" fill="none" stroke={C.gold} strokeWidth={8} strokeDasharray={1400} strokeDashoffset={1400*(1-p)}/></svg><div style={{fontSize:52,fontWeight:800,color:C.white}}>${m.intent}</div></AbsoluteFill>};\n`;
  } else if (m.family === 'css-3d') {
    body = `export const ${exp}:React.FC=()=>{const f=useCurrentFrame();const p=interpolate(f,[0,80],[0,1],clamp);return <AbsoluteFill style={{background:C.bg,perspective:1400,alignItems:'center',justifyContent:'center'}}><div style={{display:'flex',gap:120,transform:'rotateX('+(8-8*p)+'deg)'}}><div style={{width:520,height:360,borderRadius:32,background:'#151A18',border:'3px solid '+C.red,transform:'translateX('+(-120*p)+'px) rotateY('+(12*p)+'deg)',display:'grid',placeItems:'center',fontSize:54,fontWeight:900,color:C.white}}>Unternehmen</div><div style={{width:520,height:360,borderRadius:32,background:'#0D1B16',border:'3px solid '+C.green,transform:'translateX('+(120*p)+'px) rotateY('+(-12*p)+'deg)',display:'grid',placeItems:'center',fontSize:54,fontWeight:900,color:C.white}}>Fondsvermögen</div></div><div style={{position:'absolute',bottom:90,fontSize:42,color:C.mint}}>getrennt verwahrt</div></AbsoluteFill>};\n`;
  } else if (m.family === 'kinetic-type') {
    body = `export const ${exp}:React.FC=()=>{const f=useCurrentFrame();const p=interpolate(f,[0,75],[0,1],clamp);const bid=100.00+0.08*p;const ask=100.34-0.10*p;return <AbsoluteFill style={{background:C.bg,justifyContent:'center',alignItems:'center'}}><div style={{display:'flex',gap:130,alignItems:'center'}}><div style={{fontSize:105,fontWeight:900,color:C.green}}>{bid.toFixed(2)} €</div><div style={{fontSize:46,color:C.muted}}>SPREAD</div><div style={{fontSize:105,fontWeight:900,color:C.red}}>{ask.toFixed(2)} €</div></div><div style={{height:10,width:500,background:C.gold,marginTop:60,transform:'scaleX('+(1-p*0.55)+')',borderRadius:99}}/><div style={{fontSize:44,color:C.white,marginTop:40}}>${m.intent}</div></AbsoluteFill>};\n`;
  } else if (m.family === 'data-viz') {
    body = `export const ${exp}:React.FC=()=>{const f=useCurrentFrame();const p=interpolate(f,[0,90],[0,1],clamp);const values=[0.28,0.48,0.68,0.86];return <AbsoluteFill style={{background:C.bg,padding:'150px 210px'}}><div style={{fontSize:54,fontWeight:900,color:C.white,marginBottom:70}}>${m.intent}</div><div style={{display:'flex',height:520,alignItems:'flex-end',gap:70}}>{values.map((v,i)=><div key={i} style={{width:190,height:460*v*p,borderRadius:'28px 28px 8px 8px',background:i===values.length-1?C.gold:C.green,boxShadow:'0 0 45px rgba(34,224,138,.18)'}}/>)}</div><div style={{position:'absolute',bottom:100,left:210,right:210,height:4,background:'#313735'}}/></AbsoluteFill>};\n`;
  } else if (m.family === 'timeline') {
    body = `export const ${exp}:React.FC=()=>{const f=useCurrentFrame();const p=interpolate(f,[0,100],[0,1],clamp);const x=220+1480*p;return <AbsoluteFill style={{background:C.bg}}><div style={{position:'absolute',top:520,left:220,width:1480,height:8,background:'#35413C',borderRadius:8}}/><div style={{position:'absolute',top:465,left:x-45,width:90,height:90,borderRadius:24,background:C.green,boxShadow:'0 0 50px rgba(34,224,138,.35)'}}/><div style={{position:'absolute',top:370,left:220,fontSize:44,color:C.white}}>2026</div><div style={{position:'absolute',top:610,left:520,fontSize:44,color:C.red}}>↓ Markt</div><div style={{position:'absolute',top:380,left:880,fontSize:44,color:C.green}}>↑ Markt</div><div style={{position:'absolute',top:610,left:1240,fontSize:44,color:C.red}}>↓ Markt</div><div style={{position:'absolute',bottom:100,width:'100%',textAlign:'center',fontSize:48,fontWeight:800,color:C.white}}>${m.intent}</div></AbsoluteFill>};\n`;
  } else if (m.family === 'document-motion') {
    body = `export const ${exp}:React.FC=()=>{const f=useCurrentFrame();const p=interpolate(f,[0,85],[0,1],clamp);return <AbsoluteFill style={{background:C.bg,justifyContent:'center',alignItems:'center'}}><div style={{display:'flex',alignItems:'center',gap:110}}><div style={{width:430,height:500,borderRadius:30,background:'#F0EBDD',transform:'translateX('+(80*p)+'px) rotate('+(-4+4*p)+'deg)',padding:50,color:'#111',fontSize:45,fontWeight:800}}>KAUFAUFTRAG<div style={{marginTop:70,fontSize:74,color:'#125B42'}}>100 €</div></div><div style={{fontSize:90,color:C.gold,opacity:p}}>→</div><div style={{width:430,height:500,borderRadius:30,background:'#17231F',border:'3px solid '+C.green,transform:'translateX('+(-80*(1-p))+'px)',display:'grid',placeItems:'center',fontSize:64,fontWeight:900,color:C.white}}>ETF</div></div><div style={{position:'absolute',bottom:90,fontSize:44,color:C.mint}}>${m.intent}</div></AbsoluteFill>};\n`;
  } else if (m.family === 'image-composite') {
    body = `export const ${exp}:React.FC=()=>{const f=useCurrentFrame();const p=interpolate(f,[0,90],[0,1],clamp);return <AbsoluteFill style={{background:'transparent'}}><div style={{position:'absolute',inset:0,background:'radial-gradient(circle at '+(20+60*p)+'% 50%, rgba(34,224,138,.28), transparent 23%)'}}/><div style={{position:'absolute',left:180+1250*p,top:440,width:120,height:120,borderRadius:34,border:'5px solid '+C.gold,boxShadow:'0 0 40px rgba(242,198,109,.35)'}}/><div style={{position:'absolute',left:220,top:760,right:220,height:7,background:'#24342D'}}><div style={{height:'100%',width:(100*p)+'%',background:C.green}}/></div><div style={{position:'absolute',bottom:90,width:'100%',textAlign:'center',fontSize:48,fontWeight:900,color:C.white}}>${m.intent}</div></AbsoluteFill>};\n`;
  } else if (m.family === 'simulation') {
    body = `export const ${exp}:React.FC=()=>{const f=useCurrentFrame();const p=interpolate(f,[0,90],[0,1],clamp);const starts=[[260,250],[260,500],[260,750]];return <AbsoluteFill style={{background:C.bg}}>{starts.map(([sx,sy],i)=>{const x=sx+(1080-sx)*p;const y=sy+(500-sy)*p;return <div key={i} style={{position:'absolute',left:x,top:y,width:90,height:90,borderRadius:'50%',background:i===1?C.gold:C.green,boxShadow:'0 0 35px rgba(34,224,138,.25)'}}/>})}<div style={{position:'absolute',left:1050,top:350,width:500,height:300,borderRadius:40,border:'4px solid '+C.mint,display:'grid',placeItems:'center',fontSize:58,fontWeight:900,color:C.white}}>ETF-FONDS</div><div style={{position:'absolute',bottom:80,width:'100%',textAlign:'center',fontSize:46,color:C.white}}>${m.intent}</div></AbsoluteFill>};\n`;
  } else if (m.family === 'comparison') {
    body = `export const ${exp}:React.FC=()=>{const f=useCurrentFrame();const p=interpolate(f,[0,85],[0,1],clamp);return <AbsoluteFill style={{background:C.bg,flexDirection:'row'}}><div style={{width:'50%',display:'grid',placeItems:'center',borderRight:'2px solid #36433D'}}><div style={{textAlign:'center',transform:'translateY('+(30*(1-p))+'px)',opacity:p}}><div style={{fontSize:54,fontWeight:900,color:C.green}}>SEKUNDÄRMARKT</div><div style={{fontSize:72,marginTop:50,color:C.white}}>ANLEGER ↔ ETF</div></div></div><div style={{width:'50%',display:'grid',placeItems:'center'}}><div style={{textAlign:'center',transform:'translateY('+(-30*(1-p))+'px)',opacity:p}}><div style={{fontSize:54,fontWeight:900,color:C.gold}}>PRIMÄRMARKT</div><div style={{fontSize:72,marginTop:50,color:C.white}}>KORB ↔ ETF</div></div></div><div style={{position:'absolute',bottom:70,width:'100%',textAlign:'center',fontSize:42,color:C.white}}>${m.intent}</div></AbsoluteFill>};\n`;
  } else if (m.family === 'camera-journey') {
    body = `export const ${exp}:React.FC=()=>{const f=useCurrentFrame();const p=interpolate(f,[0,105],[0,1],clamp);const stages=['100 €','BÖRSE','ETF','FONDS','UNTERNEHMEN'];return <AbsoluteFill style={{background:C.bg,overflow:'hidden'}}><div style={{position:'absolute',left:0,top:0,height:'100%',width:5000,display:'flex',alignItems:'center',gap:300,transform:'translateX('+(-3100*p)+'px) scale('+(1+0.08*p)+')'}}>{stages.map((s,i)=><div key={s} style={{width:620,height:420,borderRadius:50,border:'4px solid '+(i===0?C.gold:C.green),display:'grid',placeItems:'center',fontSize:72,fontWeight:900,color:C.white,background:'#0C1512'}}>{s}</div>)}</div><div style={{position:'absolute',bottom:70,width:'100%',textAlign:'center',fontSize:44,color:C.mint}}>${m.intent}</div></AbsoluteFill>};\n`;
  } else {
    body = `export const ${exp}:React.FC=()=>{const f=useCurrentFrame();const {fps}=useVideoConfig();const p=interpolate(f,[0,90],[0,1],clamp);const s=spring({frame:f-6,fps,config:{damping:15}});return <AbsoluteFill style={{background:C.bg,justifyContent:'center',alignItems:'center'}}><div style={{width:900,height:520,borderRadius:50,border:'4px solid '+C.green,transform:'scale('+(0.85+0.15*s)+')',display:'grid',placeItems:'center',fontSize:62,fontWeight:900,color:C.white,opacity:0.35+0.65*p}}>${m.intent}</div></AbsoluteFill>};\n`;
  }
  return header + body;
};

'''

text = text[:start] + replacement + text[end:]
text = text.replace('FINANZNEO_FLOW_AGENT_PROTOCOL: finanzneo-flow-sequential-v1', 'FLOW_AGENT_PROTOCOL: finanzneo-flow-sequential-v1')
path.write_text(text, encoding='utf-8')
print('generator patched')
