import React from 'react';
import {AbsoluteFill, Audio, Sequence, interpolate, spring, staticFile, useCurrentFrame, useVideoConfig} from 'remotion';
import {FullFrameImage, FullFrameReadabilityScrim} from '../../design-system';
import {C, FONT, a, euro} from '../../brand';
import assetManifest from './asset-manifest.json';
import {NOTGROSCHEN_COPY, NOTGROSCHEN_DURATIONS, NOTGROSCHEN_TOTAL_FRAMES} from './config';
import {NotgroschenKaraokeCaptions} from './KaraokeCaptions';
import {Headline, SceneBackground, VisualStage, WorldStage, clamp01, clampInput} from './shared';

export {NOTGROSCHEN_TOTAL_FRAMES};
type ImageSceneId='scene-01'|'scene-02'|'scene-04'|'scene-06'|'scene-09'|'scene-10';

const StillScene:React.FC<{sceneId:ImageSceneId;index:number}>=({sceneId,index})=>{
  const src=(assetManifest as Record<string,string|null>)[sceneId];
  if(!src)throw new Error(`BLOCKED: Pflichtbild für ${sceneId} fehlt im synchronisierten Ziel-Reel-Asset-Manifest.`);

  return <AbsoluteFill style={{background:C.bg,overflow:'hidden'}}>
    <FullFrameImage src={staticFile(src)}/>
    <FullFrameReadabilityScrim/>
    <Headline copy={NOTGROSCHEN_COPY[index]}/>
  </AbsoluteFill>;
};

const TargetRangeAnimation:React.FC<{durationInFrames:number}>=({durationInFrames})=>{
  const frame=useCurrentFrame();const {fps}=useVideoConfig();const p=frame/Math.max(1,durationInFrames-1);
  const reveal=clamp01(spring({frame,fps,durationInFrames:Math.round(durationInFrames*.22),config:{damping:18,stiffness:160}}));
  const third=interpolate(p,[.22,.42],[0,1],clampInput);const slider=interpolate(p,[.48,.78],[.24,.78],clampInput);
  return <SceneBackground><Headline copy={NOTGROSCHEN_COPY[2]}/><VisualStage><WorldStage/><div style={{position:'absolute',top:54,left:90,right:90,textAlign:'center'}}><div style={{fontFamily:FONT.body,fontWeight:900,fontSize:28,color:C.gray}}>DAUMENREGEL</div><div style={{marginTop:24,display:'flex',justifyContent:'center',gap:24}}>{[1,2,3].map((value,i)=><div key={value} style={{width:238,height:250,borderRadius:34,display:'grid',placeItems:'center',background:i===0?'rgba(255,255,255,.045)':a(C.accent,.17),border:`2px solid ${i===0?'rgba(255,255,255,.11)':a(C.accentLt,.62)}`,opacity:i===2?third:reveal,transform:`translateY(${(1-(i===2?third:reveal))*65}px) scale(${.84+(i===2?third:reveal)*.16})`,boxShadow:i===0?'none':`0 24px 75px ${a(C.accent,.18)}`}}><div><div style={{fontFamily:FONT.title,fontSize:104,color:i===0?C.grayDk:C.accentLt}}>{value}</div><div style={{fontFamily:FONT.body,fontWeight:900,fontSize:27,color:C.white}}>MONAT{value>1?'E':''}</div></div></div>)}</div></div><div style={{position:'absolute',left:130,right:130,top:455}}><div style={{fontFamily:FONT.body,fontSize:27,fontWeight:900,color:C.white,textAlign:'center',marginBottom:24}}>PERSÖNLICH ANPASSEN</div><div style={{height:16,borderRadius:999,background:'rgba(255,255,255,.08)',position:'relative'}}><div style={{position:'absolute',left:0,top:0,bottom:0,width:`${slider*100}%`,borderRadius:999,background:`linear-gradient(90deg,${C.accent},${C.gold})`}}/><div style={{position:'absolute',left:`${slider*100}%`,top:'50%',width:48,height:48,borderRadius:'50%',transform:'translate(-50%,-50%)',background:C.white,border:`8px solid ${C.accent}`,boxShadow:`0 0 28px ${a(C.accent,.45)}`}}/></div><div style={{marginTop:38,display:'flex',justifyContent:'space-between',gap:12}}>{['STABILER JOB','KINDER','AUTO','EIGENHEIM'].map((label,i)=><div key={label} style={{flex:1,borderRadius:18,padding:'13px 8px',textAlign:'center',background:i===0?'rgba(255,255,255,.05)':a(C.gold,.1),border:`1px solid ${i===0?'rgba(255,255,255,.1)':a(C.goldLt,.35)}`,fontFamily:FONT.body,fontSize:20,fontWeight:900,color:i===0?C.gray:C.goldLt}}>{label}</div>)}</div></div></VisualStage></SceneBackground>;
};

const ThreeStageAnimation:React.FC<{durationInFrames:number}>=({durationInFrames})=>{
  const frame=useCurrentFrame();const p=frame/Math.max(1,durationInFrames-1);const active=Math.min(3,Math.max(1,Math.ceil(interpolate(p,[.12,.7],[0,3],clampInput))));
  const stages=[['1','500 €','MINI-PUFFER'],['2','1 MONAT','NOTWENDIGE AUSGABEN'],['3','2–3 MONATE','PERSÖNLICHES ZIEL']];
  return <SceneBackground><Headline copy={NOTGROSCHEN_COPY[4]}/><VisualStage><WorldStage/><div style={{position:'absolute',left:78,right:78,top:70,display:'flex',flexDirection:'column',gap:24}}>{stages.map(([n,value,label],i)=>{const reveal=interpolate(p,[.08+i*.12,.26+i*.12],[0,1],clampInput);const isActive=i<active;return <div key={n} style={{height:220,borderRadius:34,display:'grid',gridTemplateColumns:'120px 1fr',alignItems:'center',padding:'22px 30px',background:isActive?a(C.accent,.17):'rgba(255,255,255,.045)',border:`2px solid ${isActive?a(C.accentLt,.6):'rgba(255,255,255,.1)'}`,opacity:reveal,transform:`translateX(${(1-reveal)*70}px)`,boxShadow:isActive?`0 24px 74px ${a(C.accent,.16)}`:'none'}}><div style={{width:84,height:84,borderRadius:'50%',display:'grid',placeItems:'center',fontFamily:FONT.title,fontSize:55,color:isActive?C.bg:C.grayDk,background:isActive?C.accentLt:'rgba(255,255,255,.07)'}}>{n}</div><div><div style={{fontFamily:FONT.title,fontSize:i===2?66:78,color:i===0?C.goldLt:C.white}}>{value}</div><div style={{fontFamily:FONT.body,fontSize:i===1?25:28,fontWeight:900,color:isActive?C.accentLt:C.gray,letterSpacing:.8}}>{label}</div></div></div>})}</div></VisualStage></SceneBackground>;
};

const ExampleTargetAnimation:React.FC<{durationInFrames:number}>=({durationInFrames})=>{
  const frame=useCurrentFrame();const {fps}=useVideoConfig();const p=frame/Math.max(1,durationInFrames-1);const source=clamp01(spring({frame,fps,durationInFrames:Math.round(durationInFrames*.2),config:{damping:18,stiffness:160}}));const results=interpolate(p,[.3,.68],[0,1],clampInput);
  return <SceneBackground><Headline copy={NOTGROSCHEN_COPY[6]}/><VisualStage><WorldStage/><div style={{position:'absolute',top:55,left:'50%',transform:`translateX(-50%) scale(${.8+source*.2})`,opacity:source,borderRadius:32,padding:'20px 42px',background:a(C.gold,.18),border:`2px solid ${a(C.goldLt,.6)}`,textAlign:'center'}}><div style={{fontFamily:FONT.body,fontSize:25,fontWeight:900,color:C.goldLt}}>BEISPIEL</div><div style={{fontFamily:FONT.title,fontSize:92,color:C.white}}>1.800 €</div><div style={{fontFamily:FONT.body,fontSize:26,fontWeight:900,color:C.gray}}>NETTO PRO MONAT</div></div><div style={{position:'absolute',top:410,left:65,right:65,display:'grid',gridTemplateColumns:'1fr 1fr',gap:24}}>{[[2,3600],[3,5400]].map(([factor,result],i)=><div key={factor} style={{height:300,borderRadius:38,padding:28,textAlign:'center',background:i===0?a(C.accent,.17):a(C.gold,.14),border:`2px solid ${i===0?a(C.accentLt,.62):a(C.goldLt,.55)}`,opacity:results,transform:`translateY(${(1-results)*70}px) scale(${.84+results*.16})`}}><div style={{fontFamily:FONT.body,fontWeight:900,fontSize:28,color:C.gray}}>1.800 € × {factor}</div><div style={{fontFamily:FONT.title,fontSize:104,color:i===0?C.accentLt:C.goldLt}}>{euro(result)}</div><div style={{fontFamily:FONT.body,fontWeight:900,fontSize:24,color:C.white}}>BEISPIELZIEL</div></div>)}</div></VisualStage></SceneBackground>;
};

const SavingsTimelineAnimation:React.FC<{durationInFrames:number}>=({durationInFrames})=>{
  const frame=useCurrentFrame();const p=frame/Math.max(1,durationInFrames-1);const line=interpolate(p,[.16,.76],[0,1],clampInput);const month=Math.round(line*24);const amount=month*150;
  return <SceneBackground><Headline copy={NOTGROSCHEN_COPY[7]}/><VisualStage><WorldStage/><div style={{position:'absolute',top:50,left:'50%',transform:'translateX(-50%)',width:430,height:170,borderRadius:36,display:'grid',placeItems:'center',background:a(C.gold,.16),border:`2px solid ${a(C.goldLt,.58)}`}}><div style={{textAlign:'center'}}><div style={{fontFamily:FONT.title,fontSize:88,color:C.goldLt}}>150 €</div><div style={{fontFamily:FONT.body,fontWeight:900,fontSize:27,color:C.white}}>PRO MONAT</div></div></div><div style={{position:'absolute',top:345,left:100,right:100}}><div style={{display:'flex',justifyContent:'space-between',fontFamily:FONT.body,fontWeight:900,fontSize:25,color:C.gray,marginBottom:20}}><span>MONAT 0</span><span>MONAT 24</span></div><div style={{height:18,borderRadius:999,background:'rgba(255,255,255,.08)',position:'relative'}}><div style={{height:'100%',width:`${line*100}%`,borderRadius:999,background:`linear-gradient(90deg,${C.gold},${C.accentLt})`,boxShadow:`0 0 26px ${a(C.accent,.35)}`}}/><div style={{position:'absolute',left:`${line*100}%`,top:'50%',width:42,height:42,borderRadius:'50%',transform:'translate(-50%,-50%)',background:C.white,border:`7px solid ${C.accent}`}}/></div><div style={{marginTop:28,textAlign:'center',fontFamily:FONT.title,fontSize:78,color:C.white}}>{euro(amount)}</div></div><div style={{position:'absolute',top:600,left:75,right:75,display:'grid',gridTemplateColumns:'1fr 1fr',gap:24}}>{[[4,'500 €','IM 4. MONAT'],[24,'3.600 €','NACH 24 MONATEN']].map(([target,value,label],i)=>{const reached=month>=Number(target);return <div key={String(target)} style={{height:220,borderRadius:34,padding:24,textAlign:'center',background:reached?a(C.accent,.18):'rgba(255,255,255,.045)',border:`2px solid ${reached?a(C.accentLt,.62):'rgba(255,255,255,.1)'}`,transform:`scale(${reached?1:.94})`}}><div style={{fontFamily:FONT.title,fontSize:76,color:reached?(i===0?C.goldLt:C.accentLt):C.grayDk}}>{value}</div><div style={{fontFamily:FONT.body,fontSize:24,fontWeight:900,color:reached?C.white:C.grayDk}}>{label}</div></div>})}</div></VisualStage></SceneBackground>;
};

const scene=(index:number,duration:number)=>{switch(index){case 0:return <StillScene sceneId="scene-01" index={0}/>;case 1:return <StillScene sceneId="scene-02" index={1}/>;case 2:return <TargetRangeAnimation durationInFrames={duration}/>;case 3:return <StillScene sceneId="scene-04" index={3}/>;case 4:return <ThreeStageAnimation durationInFrames={duration}/>;case 5:return <StillScene sceneId="scene-06" index={5}/>;case 6:return <ExampleTargetAnimation durationInFrames={duration}/>;case 7:return <SavingsTimelineAnimation durationInFrames={duration}/>;case 8:return <StillScene sceneId="scene-09" index={8}/>;case 9:return <StillScene sceneId="scene-10" index={9}/>;default:return null;}};

export const NotgroschenStufenplan:React.FC=()=>{let from=0;const audio=(assetManifest as {audio:string|null}).audio;if(!audio)throw new Error('BLOCKED: Finales Voiceover fehlt im synchronisierten Ziel-Reel-Asset-Manifest.');return <AbsoluteFill style={{background:C.bg}}><Audio src={staticFile(audio)} volume={1}/>{NOTGROSCHEN_DURATIONS.map((duration,index)=>{const start=from;from+=duration;return <Sequence key={index} from={start} durationInFrames={duration}>{scene(index,duration)}</Sequence>})}<NotgroschenKaraokeCaptions/></AbsoluteFill>;
};
