import React from 'react';
import {AbsoluteFill,Img,staticFile} from 'remotion';
import {C,FONT} from '../../brand';
export const L={headerTop:48,headerBottom:230,animTop:242,animBottom:1390,captionBottom:430,captionLeft:72,captionRight:170,squareTop:265,squareLeft:40,squareSize:1000} as const;
export const Bg:React.FC=()=> <AbsoluteFill style={{background:'radial-gradient(circle at 50% 42%,#123a25 0%,#07180f 49%,#020805 100%)'}}/>;
export const Header:React.FC<{headline:string;subheadline:string}>=({headline,subheadline})=><div style={{position:'absolute',left:62,right:82,top:L.headerTop,height:L.headerBottom-L.headerTop,zIndex:30,display:'flex',flexDirection:'column',justifyContent:'center'}}><div style={{fontFamily:FONT.heading,fontSize:64,lineHeight:.93,fontWeight:900,color:C.white,textTransform:'uppercase',textShadow:'0 4px 20px rgba(0,0,0,.58)'}}>{headline}</div><div style={{fontFamily:FONT.body,fontSize:31,lineHeight:1.13,fontWeight:700,color:C.graySoft,marginTop:13,textShadow:'0 3px 14px rgba(0,0,0,.48)'}}>{subheadline}</div></div>;
export const SquareImage:React.FC<{scene:number;storyboard?:boolean}>=({scene,storyboard=false})=>{if(storyboard)return <div style={{position:'absolute',left:L.squareLeft,top:L.squareTop,width:L.squareSize,height:L.squareSize,borderRadius:42,background:'linear-gradient(145deg,rgba(0,210,106,.22),rgba(255,200,61,.12))',border:'2px solid rgba(255,255,255,.12)',display:'flex',alignItems:'center',justifyContent:'center',fontFamily:FONT.heading,fontSize:52,fontWeight:900,color:C.white,textAlign:'center'}}>STORYBOARD 1:1<br/>BILD {String(scene).padStart(2,'0')}</div>;return <Img src={staticFile(`reels/25-euro-mehr-sparrate/scene-${String(scene).padStart(2,'0')}.png`)} style={{position:'absolute',left:L.squareLeft,top:L.squareTop,width:L.squareSize,height:L.squareSize,objectFit:'cover',borderRadius:42}}/>;};
export const AnimStage:React.FC<{children:React.ReactNode}>=({children})=><div style={{position:'absolute',left:0,right:0,top:L.animTop,height:L.animBottom-L.animTop,overflow:'hidden',zIndex:10}}>{children}</div>;
export const Shell:React.FC<{headline:string;subheadline:string;children:React.ReactNode;image?:boolean}>=({headline,subheadline,children,image=false})=><AbsoluteFill><Bg/>{image?children:<AnimStage>{children}</AnimStage>}<Header headline={headline} subheadline={subheadline}/></AbsoluteFill>;
