import type {NarrativeScenePlan} from './NarrativeAnimationQuality';

/**
 * Retrospektive Beschreibung des ersten Full-Animation-Reels.
 * Diese Liste ist absichtlich als abgelehntes Referenzbeispiel erhalten.
 * Sie dokumentiert den Fehler: technisch verschiedene Komponenten, aber fast
 * durchgehend derselbe Vergleich in Dashboard- und Datenvisualisierungsform.
 */
export const REJECTED_EARLY_VS_LATE_PLAN = [
  {
    id: 'early-vs-late-race',
    contentBeat: '100 Euro ab 20 gegen 200 Euro ab 30',
    primarySubject: 'Person A und Person B',
    narrativeAction: 'zwei Werte fahren auf Linien',
    visualMetaphor: 'Finanzrennen',
    startState: 'beide Werte am Start',
    endState: 'beide Werte am Ziel',
    visualMode: 'data-viz',
    layoutFamily: 'track-race',
    cameraMove: 'static',
    transitionOut: 'harter Schnitt',
    dataViz: true,
    dashboardFraming: true,
    repeatsCoreComparison: true,
  },
  {
    id: 'dual-contribution-timeline',
    contentBeat: 'Einzahlungen von Person A und Person B',
    primarySubject: 'Person A und Person B',
    narrativeAction: 'zwei Fortschrittslinien wachsen',
    visualMetaphor: 'doppelte Zeitachse',
    startState: 'leere Linien',
    endState: 'gefüllte Linien',
    visualMode: 'data-viz',
    layoutFamily: 'timeline',
    cameraMove: 'static',
    transitionOut: 'harter Schnitt',
    dataViz: true,
    dashboardFraming: true,
    repeatsCoreComparison: true,
  },
  {
    id: 'contribution-result-flip',
    contentBeat: 'Person A liegt trotz weniger Einzahlung vorne',
    primarySubject: 'Person A und Person B',
    narrativeAction: 'zwei Balken ändern ihre Höhe',
    visualMetaphor: 'Balkenwaage',
    startState: 'Person B erscheint größer',
    endState: 'Person A erscheint größer',
    visualMode: 'data-viz',
    layoutFamily: 'dashboard-card',
    cameraMove: 'static',
    transitionOut: 'harter Schnitt',
    dataViz: true,
    dashboardFraming: true,
    repeatsCoreComparison: true,
  },
  {
    id: 'compound-engine',
    contentBeat: 'Zinseszins ist der Grund',
    primarySubject: 'Münzen und Zahnräder',
    narrativeAction: 'Münzen kreisen um einen Motor',
    visualMetaphor: 'Zinseszins-Motor',
    startState: 'eine Münze',
    endState: 'mehrere Münzen',
    visualMode: 'process-machine',
    layoutFamily: 'machine',
    cameraMove: 'static',
    transitionOut: 'harter Schnitt',
    dataViz: false,
    dashboardFraming: true,
    repeatsCoreComparison: false,
  },
  {
    id: 'delayed-growth-race',
    contentBeat: 'Endwerte von Person A und Person B',
    primarySubject: 'Person A und Person B',
    narrativeAction: 'zwei Kurven werden gezeichnet',
    visualMetaphor: 'Wachstumskurven',
    startState: 'leeres Diagramm',
    endState: 'zwei Endwerte',
    visualMode: 'data-viz',
    layoutFamily: 'chart',
    cameraMove: 'static',
    transitionOut: 'harter Schnitt',
    dataViz: true,
    dashboardFraming: true,
    repeatsCoreComparison: true,
  },
  {
    id: 'capital-composition-reveal',
    contentBeat: 'Endwerte von Person A und Person B',
    primarySubject: 'Person A und Person B',
    narrativeAction: 'zwei gestapelte Balken wachsen',
    visualMetaphor: 'Kapitalbalken',
    startState: 'leere Balken',
    endState: 'Einzahlung und Wachstum sind sichtbar',
    visualMode: 'data-viz',
    layoutFamily: 'dashboard-card',
    cameraMove: 'static',
    transitionOut: 'harter Schnitt',
    dataViz: true,
    dashboardFraming: true,
    repeatsCoreComparison: true,
  },
  {
    id: 'time-advantage-finale',
    contentBeat: 'Früher anfangen ist wichtiger',
    primarySubject: 'Uhr und Wachstumslinie',
    narrativeAction: 'eine Linie wächst neben einer Uhr',
    visualMetaphor: 'Zeit als Hebel',
    startState: 'Uhr bei Alter 20',
    endState: 'Wachstumslinie erreicht das Ziel',
    visualMode: 'kinetic-type',
    layoutFamily: 'dashboard-card',
    cameraMove: 'static',
    transitionOut: 'Ausblende',
    dataViz: false,
    dashboardFraming: true,
    repeatsCoreComparison: true,
  },
] as const satisfies readonly NarrativeScenePlan[];

/**
 * Positives Referenz-Storyboard. Es ist noch kein Produktionsreel, sondern die
 * verbindliche Form, in der ein neues Skript vor der Programmierung geplant
 * und durch das Quality Gate geschickt werden muss.
 */
export const NARRATIVE_REEL_REFERENCE_PLAN = [
  {
    id: 'salary-package-arrives',
    contentBeat: 'Das Nettogehalt kommt auf dem Konto an',
    primarySubject: 'ein 3.000-Euro-Geldpaket',
    narrativeAction: 'das Geldpaket landet und fährt durch die Szene',
    visualMetaphor: 'Gehalt als physisches Paket',
    startState: 'leeres Förderband',
    endState: 'das vollständige Gehalt liegt sichtbar bereit',
    visualMode: 'object-story',
    layoutFamily: 'full-bleed-world',
    cameraMove: 'follow-subject',
    transitionOut: 'das Paket fährt direkt in das nächste Gebäude',
    dataViz: false,
    dashboardFraming: false,
    repeatsCoreComparison: false,
  },
  {
    id: 'rent-removes-largest-piece',
    contentBeat: 'Die Miete nimmt den größten Teil des Gehalts',
    primarySubject: 'Wohnblock und Geldpaket',
    narrativeAction: 'der Wohnblock zieht einen großen Geldblock aus dem Paket',
    visualMetaphor: 'Miete als schweres Gebäude',
    startState: 'volles Geldpaket vor dem Wohnblock',
    endState: 'ein deutlich kleineres Paket verlässt das Gebäude',
    visualMode: 'environment',
    layoutFamily: 'spatial-stage',
    cameraMove: 'push-in',
    transitionOut: 'der entfernte Geldblock wird zur nächsten Szenenwand',
    dataViz: false,
    dashboardFraming: false,
    repeatsCoreComparison: false,
  },
  {
    id: 'subscriptions-nibble-away',
    contentBeat: 'Viele kleine Verträge summieren sich',
    primarySubject: 'Abo- und Versicherungsobjekte',
    narrativeAction: 'kleine Objekte beißen nacheinander Stücke aus dem Restbetrag',
    visualMetaphor: 'Verträge als kleine Geldfresser',
    startState: 'ein noch großer Restbetrag',
    endState: 'viele kleine Bisse haben eine große Lücke erzeugt',
    visualMode: 'transformation',
    layoutFamily: 'split-screen',
    cameraMove: 'pan',
    transitionOut: 'ein Geldstück rollt in den Einkaufswagen',
    dataViz: false,
    dashboardFraming: false,
    repeatsCoreComparison: false,
  },
  {
    id: 'inflation-shrinks-shopping-cart',
    contentBeat: 'Inflation senkt die reale Kaufkraft',
    primarySubject: 'Einkaufswagen und Produkte',
    narrativeAction: 'Preisschilder wachsen, während Produkte aus dem Wagen verschwinden',
    visualMetaphor: 'gleicher Geldschein kauft einen kleineren Warenkorb',
    startState: 'voller Einkaufswagen mit altem Preis',
    endState: 'halb leerer Einkaufswagen mit höherem Preis',
    visualMode: 'environment',
    layoutFamily: 'full-bleed-world',
    cameraMove: 'follow-subject',
    transitionOut: 'das letzte Preisschild klappt zur Kalenderseite um',
    dataViz: false,
    dashboardFraming: false,
    repeatsCoreComparison: false,
  },
  {
    id: 'future-income-chained-by-installments',
    contentBeat: 'Ratenkäufe binden zukünftiges Einkommen',
    primarySubject: 'kommende Gehaltspakete und Ratenketten',
    narrativeAction: 'Ketten verbinden zukünftige Monate mit heutigen Käufen',
    visualMetaphor: 'zukünftiges Gehalt ist bereits angekettet',
    startState: 'freie zukünftige Monatsgehälter',
    endState: 'mehrere Monate tragen feste Ratenketten',
    visualMode: 'time-travel',
    layoutFamily: 'timeline',
    cameraMove: 'pull-out',
    transitionOut: 'eine Kette wird in der nächsten Szene durchtrennt',
    dataViz: false,
    dashboardFraming: false,
    repeatsCoreComparison: false,
  },
  {
    id: 'budget-machine-reorders-money',
    contentBeat: 'Automatisches Sparen und Vertragsbereinigung schaffen Kontrolle',
    primarySubject: 'eine Budget-Sortiermaschine',
    narrativeAction: 'die Maschine entfernt unnötige Verträge und leitet Spargeld zuerst ab',
    visualMetaphor: 'Budget als Sortieranlage',
    startState: 'ungeordneter Geldstrom mit Lecks',
    endState: 'klar getrennte Töpfe für Fixkosten, Sparen und Freizeit',
    visualMode: 'process-machine',
    layoutFamily: 'machine',
    cameraMove: 'orbit',
    transitionOut: 'die drei Geldströme formen das Abschlussdiagramm',
    dataViz: false,
    dashboardFraming: false,
    repeatsCoreComparison: false,
  },
  {
    id: 'before-after-proof',
    contentBeat: 'Die Maßnahmen erhöhen den freien Monatsbetrag',
    primarySubject: 'Vorher- und Nachher-Cashflow',
    narrativeAction: 'ein einziges Beweisdiagramm zeigt den gewonnenen Überschuss',
    visualMetaphor: 'ein Leck wird zu einem stabilen Sparstrom',
    startState: 'kleiner oder negativer Monatsüberschuss',
    endState: 'sichtbar höherer positiver Monatsüberschuss',
    visualMode: 'data-viz',
    layoutFamily: 'chart',
    cameraMove: 'push-in',
    transitionOut: 'der positive Balken wird zum finalen Sparziel',
    dataViz: true,
    dashboardFraming: true,
    repeatsCoreComparison: false,
  },
] as const satisfies readonly NarrativeScenePlan[];
