import React from 'react';
import {AbsoluteFill, interpolate, spring, useCurrentFrame, useVideoConfig} from 'remotion';
import {C, FONT} from '../../brand';

const clamp={extrapolateLeft:'clamp' as const,extrapolateRight:'clamp' as const};
const prog=(f:number,d:number,a=.06,b=.9)=>interpolate(f,[d*a,d*b],[0,1],clamp);
const euro=(v:number)=>`${Math.max(0,Math.round(v)).toLocaleString('de-DE')} €`;

const DebtTank:React.FC<{value:number;max?:number;label?:string;color?:string}>=({value,max=1500,label='RESTSCHULD',color=C.negativeLt})=>{const fill=Math.max(0,Math.min(1,value/max));return <div style={{width:360,height:650,position:'relative',display:'flex',flexDirection:'column',alignItems:'center'}}><div style={{fontFamily:FONT.heading,fontSize:34,fontWeight:900,color,marginBottom:14}}>{label}</div><div style={{width:300,height:470,borderRadius:82,border:'3px solid rgba(255,255,255,.18)',background:'rgba(255,255,255,.035)',overflow:'hidden',position:'relative',boxShadow:'inset 0 0 55px rgba(0,0,0,.34),0 35px 80px rgba(0,0,0,.28)'}}><div style={{position:'absolute',left:0,right:0,bottom:0,height:`${fill*100}%`,background:`linear-gradient(180deg,${color},#6f1026)`,boxShadow:'0 -12px 36px rgba(255,70,70,.28)'}}/><div style={{position:'absolute',left:28,right:28,top:42,height:10,borderRadius:6,background:'rgba(255,255,255,.17)'}}/></div><div style={{fontFamily:FONT.heading,fontSize:48,fontWeight:900,color:C.white,marginTop:14}}>{euro(value)}</div></div>};

const PayToken:React.FC<{label:string;scale?:number;color?:string}>=({label,scale=1,color=C.gold})=><div style={{width:220,height:220,borderRadius:'50%',transform:`scale(${scale})`,background:`radial-gradient(circle at 30% 25%,#fff5c7 0%,${color} 28%,#b87900 72%,#704500 100%)`,border:'7px solid rgba(255,235,170,.72)',boxShadow:'0 36px 85px rgba(255,200,61,.24)',display:'flex',alignItems:'center',justifyContent:'center',fontFamily:FONT.heading,fontSize:52,fontWeight:900,color:'#201300'}}>{label}</div>;

export const RevolvingBalanceAnimation:React.FC<{durationFrames:number}>=({durationFrames})=>{const f=useCurrentFrame();const p=prog(f,durationFrames,.05,.92);const phase=(p*3)%1;const month=Math.min(3,Math.floor(p*3)+1);const balance=[1500,1472.5,1444.59,1416.25][Math.min(3,Math.floor(p*3))];return <AbsoluteFill style={{alignItems:'center',justifyContent:'center'}}><div style={{width:1020,height:980,position:'relative'}}><div style={{position:'absolute',left:65,top:315}}><DebtTank value={balance}/></div><div style={{position:'absolute',right:35,top:275,width:440,height:440,borderRadius:'50%',border:'22px solid rgba(255,107,107,.18)',boxShadow:'inset 0 0 70px rgba(176,16,48,.2)',transform:`rotate(${p*310}deg)`}}><div style={{position:'absolute',right:-25,top:170,width:80,height:80,borderRadius:'50%',background:C.negativeLt,boxShadow:'0 0 45px rgba(255,80,80,.5)'}}/></div><div style={{position:'absolute',right:145,top:368,transform:`translate(${interpolate(phase,[0,1],[120,-130])}px,${interpolate(phase,[0,.5,1],[-100,20,110])}px) scale(${.85+.15*Math.sin(phase*Math.PI)})`}}><PayToken label="50 €" scale=.78/></div><div style={{position:'absolute',right:105,top:210,fontFamily:FONT.heading,fontSize:42,fontWeight:900,color:C.white}}>MONAT {month}</div><div style={{position:'absolute',left:410,right:100,bottom:80,fontFamily:FONT.heading,fontSize:43,lineHeight:1,fontWeight:900,color:C.white,textAlign:'center'}}>RATE REIN → REST BLEIBT → NÄCHSTER MONAT</div></div></AbsoluteFill>};

export const RateSplitAnimation:React.FC<{durationFrames:number}>=({durationFrames})=>{const f=useCurrentFrame();const p=prog(f,durationFrames,.08,.88);const split=prog(f,durationFrames,.28,.72);return <AbsoluteFill style={{alignItems:'center',justifyContent:'center'}}><div style={{width:1020,height:980,position:'relative'}}><div style={{position:'absolute',left:75,top:355,transform:`translateX(${interpolate(p,[0,1],[-60,160])}px)`}}><PayToken label="50 €"/></div><div style={{position:'absolute',left:435,top:410,width:80,height:80,borderRadius:26,background:C.white,transform:`rotate(${45*split}deg)`,boxShadow:'0 0 40px rgba(255,255,255,.26)'}}/><div style={{position:'absolute',right:40,top:190,width:330,height:280,borderRadius:70,background:'linear-gradient(145deg,#ff806c,#97152f)',display:'flex',flexDirection:'column',alignItems:'center',justifyContent:'center',boxShadow:'0 32px 80px rgba(176,16,48,.25)',transform:`translateY(${interpolate(split,[0,1],[60,0])}px)`,opacity:split}}><div style={{fontFamily:FONT.body,fontSize:27,fontWeight:900,color:C.white}}>ZINS</div><div style={{fontFamily:FONT.heading,fontSize:66,fontWeight:900,color:C.white}}>22,50 €</div></div><div style={{position:'absolute',right:40,bottom:135,width:330,height:280,borderRadius:70,background:'linear-gradient(145deg,#7bffc0,#00803f)',display:'flex',flexDirection:'column',alignItems:'center',justifyContent:'center',boxShadow:'0 32px 80px rgba(0,210,106,.22)',transform:`translateY(${interpolate(split,[0,1],[-60,0])}px)`,opacity:split}}><div style={{fontFamily:FONT.body,fontSize:27,fontWeight:900,color:'#052410'}}>TILGUNG</div><div style={{fontFamily:FONT.heading,fontSize:62,fontWeight:900,color:'#052410'}}>27,50 €</div></div><div style={{position:'absolute',left:30,right:390,bottom:70,textAlign:'center',fontFamily:FONT.body,fontSize:29,fontWeight:900,color:C.graySoft}}>18 % / 12 = 1,5 % MODELLZINS PRO MONAT</div></div></AbsoluteFill>};

const calcBalance=(months:number,payment:number)=>{let b=1500;for(let i=0;i<months&&b>0;i++){b=Math.max(0,b+b*.18/12-payment)}return b};

export const SlowDebtDrainAnimation:React.FC<{durationFrames:number}>=({durationFrames})=>{const f=useCurrentFrame();const p=prog(f,durationFrames,.05,.92);const month=Math.round(p*12);const b=calcBalance(month,50);const pulse=(f%24)/24;return <AbsoluteFill style={{alignItems:'center',justifyContent:'center'}}><div style={{width:1020,height:980,position:'relative'}}><div style={{position:'absolute',left:80,top:160}}><DebtTank value={b}/></div><div style={{position:'absolute',right:40,top:180,width:450,height:600}}>{Array.from({length:12}).map((_,i)=>{const active=i<month;return <div key={i} style={{height:42,marginBottom:8,borderRadius:22,background:active?'linear-gradient(90deg,#ff6b6b,#ffc83d,#00d26a)':'rgba(255,255,255,.07)',opacity:active?1:.28,display:'flex',alignItems:'center',padding:'0 18px',fontFamily:FONT.body,fontSize:22,fontWeight:900,color:C.white}}>{i+1}. MONAT {active?'· ZINS + RATE':''}</div>})}</div><div style={{position:'absolute',left:390,top:345,transform:`scale(${.85+.18*Math.sin(pulse*Math.PI)})`}}><PayToken label="50 €" scale=.65/></div><div style={{position:'absolute',left:35,right:35,bottom:35,textAlign:'center',fontFamily:FONT.heading,fontSize:42,fontWeight:900,color:C.white}}>12 RATEN – UND DIE SCHULD IST NOCH NICHT WEG</div></div></AbsoluteFill>};

export const FortyOneMonthsAnimation:React.FC<{durationFrames:number}>=({durationFrames})=>{const f=useCurrentFrame();const p=prog(f,durationFrames,.04,.94);const month=Math.min(41,Math.floor(p*41));const b=calcBalance(month,50);const page=Math.floor(p*14);return <AbsoluteFill style={{alignItems:'center',justifyContent:'center'}}><div style={{width:1020,height:980,position:'relative'}}><div style={{position:'absolute',left:70,top:170}}><DebtTank value={b}/></div><div style={{position:'absolute',right:65,top:190,width:410,height:520,borderRadius:70,background:'linear-gradient(180deg,rgba(255,255,255,.12),rgba(255,255,255,.035))',border:'2px solid rgba(255,255,255,.15)',boxShadow:'0 35px 80px rgba(0,0,0,.28)',display:'flex',flexDirection:'column',alignItems:'center',justifyContent:'center'}}><div style={{fontFamily:FONT.body,fontSize:28,fontWeight:900,color:C.graySoft}}>MONAT</div><div style={{fontFamily:FONT.heading,fontSize:150,fontWeight:900,color:month>=41?C.accentLt:C.white}}>{month}</div><div style={{fontFamily:FONT.heading,fontSize:42,fontWeight:900,color:month>=41?C.accentLt:C.goldLt}}>{month>=41?'SCHULD = 0 €':'NOCH OFFEN'}</div>{Array.from({length:5}).map((_,i)=><div key={i} style={{position:'absolute',left:45+i*58,top:28,width:38,height:38,borderRadius:'50%',background:i<=page%5?C.gold:'rgba(255,255,255,.14)',transform:`translateY(${i===page%5?-6:0}px)`}}/>)}</div><div style={{position:'absolute',left:40,right:40,bottom:60,height:22,borderRadius:11,background:'rgba(255,255,255,.08)',overflow:'hidden'}}><div style={{height:'100%',width:`${p*100}%`,background:`linear-gradient(90deg,${C.negativeLt},${C.gold},${C.accent})`}}/></div></div></AbsoluteFill>};

export const RateRaceAnimation:React.FC<{durationFrames:number}>=({durationFrames})=>{const f=useCurrentFrame();const p=prog(f,durationFrames,.04,.94);const m=Math.floor(p*41);const b50=calcBalance(m,50);const b100=calcBalance(Math.min(m,18),100);return <AbsoluteFill style={{alignItems:'center',justifyContent:'center'}}><div style={{width:1040,height:980,position:'relative',display:'flex',alignItems:'center',justifyContent:'space-around'}}><div style={{display:'flex',flexDirection:'column',alignItems:'center'}}><DebtTank value={b50} label="50 € RATE" color={C.negativeLt}/><div style={{fontFamily:FONT.heading,fontSize:37,fontWeight:900,color:C.negativeLt}}>≈ 41 MONATE</div></div><div style={{width:5,height:680,borderRadius:3,background:'rgba(255,255,255,.12)'}}/><div style={{display:'flex',flexDirection:'column',alignItems:'center'}}><DebtTank value={b100} label="100 € RATE" color={C.accent}/><div style={{fontFamily:FONT.heading,fontSize:37,fontWeight:900,color:C.accentLt}}>≈ 18 MONATE</div></div><div style={{position:'absolute',left:0,right:0,bottom:20,textAlign:'center',fontFamily:FONT.body,fontSize:27,fontWeight:900,color:C.graySoft}}>GLEICHE STARTSCHULD · GLEICHER MODELLZINS</div></div></AbsoluteFill>};

const InterestPile:React.FC<{value:number;max:number;label:string}>=({value,max,label})=>{const n=Math.round(3+12*value/max);return <div style={{width:390,height:650,position:'relative',display:'flex',flexDirection:'column',alignItems:'center',justifyContent:'end'}}><div style={{fontFamily:FONT.heading,fontSize:36,fontWeight:900,color:C.white,position:'absolute',top:15}}>{label}</div><div style={{height:430,width:320,position:'relative'}}>{Array.from({length:15}).map((_,i)=>{const active=i<n;return <div key={i} style={{position:'absolute',left:30+(i%2)*12,bottom:i*24,width:260,height:42,borderRadius:22,background:active?'linear-gradient(180deg,#ff9078,#b01030)':'rgba(255,255,255,.05)',border:'2px solid rgba(255,130,110,.35)',opacity:active?1:.08,boxShadow:active?'0 10px 24px rgba(176,16,48,.2)':'none'}}/>})}</div><div style={{fontFamily:FONT.heading,fontSize:58,fontWeight:900,color:C.negativeLt}}>{euro(value)}</div></div>};

export const InterestComparisonAnimation:React.FC<{durationFrames:number}>=({durationFrames})=>{const f=useCurrentFrame();const p=prog(f,durationFrames,.05,.9);const a=508*p;const b=212*p;return <AbsoluteFill style={{alignItems:'center',justifyContent:'center'}}><div style={{width:1030,height:980,position:'relative',display:'flex',alignItems:'center',justifyContent:'space-around'}}><InterestPile value={a} max={508} label="50 € RATE"/><InterestPile value={b} max={508} label="100 € RATE"/><div style={{position:'absolute',left:260,right:260,bottom:28,textAlign:'center',fontFamily:FONT.heading,fontSize:53,fontWeight:900,color:C.goldLt}}>DIFFERENZ ≈ {euro(296*p)}</div></div></AbsoluteFill>};
